// src/ui-svelte-dom/EditableValueView.svelte
<script lang="ts">
  import type {
    EditableValueView as EditableValueViewDecl,
  } from '../@types/ui-svelte-dom/index.d.ts';
  import type {ValueViewProps} from '../@types/ui-svelte/index.d.ts';
  import {VALUE} from '../common/strings.ts';
  import {getValue, resolveStore} from '../ui-svelte/functions.svelte.ts';
  import EditableThing from './common/EditableThing.svelte';
  import {EDITABLE} from './common/index.ts';

  let {
    valueId,
    store,
    className,
    showType,
  }: ValueViewProps & {
    readonly className?: string;
    readonly showType?: boolean;
  } = $props();

  const value = getValue(
    () => valueId,
    () => store,
  );
  const resolvedStore = resolveStore(() => store);
</script>

<EditableThing
  thing={value.current}
  onThingChange={(thing) => (value.current = thing)}
  className={className ?? EDITABLE + VALUE}
  {showType}
  hasSchema={() => resolvedStore()?.hasValuesSchema() ?? false}
/>

// src/ui-react-dom/EditableValueView.tsx
import type {Value} from '../@types/index.js';
import type {EditableValueView as EditableValueViewDecl} from '../@types/ui-react-dom/index.js';
import type {ValueProps} from '../@types/ui-react/index.js';
import {VALUE} from '../common/strings.ts';
import {
  useSetValueCallback,
  useStoreOrStoreById,
  useValue,
} from '../ui-react/hooks.ts';
import {EDITABLE, EditableThing} from './common.tsx';

export const EditableValueView: typeof EditableValueViewDecl = ({
  valueId,
  store,
  className,
  showType,
}: ValueProps & {readonly className?: string; readonly showType?: boolean}) => (
  <EditableThing
    thing={useValue(valueId, store)}
    onThingChange={useSetValueCallback(
      valueId,
      (value: Value) => value,
      [],
      store,
    )}
    className={className ?? EDITABLE + VALUE}
    showType={showType}
    hasSchema={useStoreOrStoreById(store)?.hasValuesSchema}
  />
);
