// src/ui-solid-dom/ResultSortedTableInHtmlTable.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  HtmlTableProps,
  ResultSortedTableInHtmlTable as ResultSortedTableInHtmlTableDecl,
  ResultSortedTableInHtmlTableProps,
} from '../@types/ui-solid-dom/index.d.ts';
import {ResultCellView} from '../ui-solid/index.ts';
import {
  useResultRowCount,
  useResultSortedRowIds,
  useResultTableCellIds,
} from '../ui-solid/primitives.ts';
import {HtmlTable} from './common/components.tsx';
import {
  getParams,
  getQueriesCellComponentProps,
  useCells,
} from './common/hooks.tsx';
import {useSortingAndPagination} from './SortedTablePaginator.tsx';

export const ResultSortedTableInHtmlTable: typeof ResultSortedTableInHtmlTableDecl =
  (props: ResultSortedTableInHtmlTableProps & HtmlTableProps): JSXElement => {
    const [sortAndOffset, handleSort, paginatorComponent] =
      useSortingAndPagination(
        () => props.cellId,
        () => props.descending,
        () => props.sortOnClick,
        () => props.offset,
        () => props.limit,
        useResultRowCount(
          () => props.queryId,
          () => props.queries,
        ),
        () => props.paginator ?? false,
        () => props.onChange,
      );
    return (
      <HtmlTable
        {...props}
        params={getParams(
          useCells(
            useResultTableCellIds(
              () => props.queryId,
              () => props.queries,
            ),
            () => props.customCells,
            () => ResultCellView,
          ),
          getQueriesCellComponentProps(
            () => props.queries,
            () => props.queryId,
          ),
          useResultSortedRowIds(
            () => props.queryId,
            () => sortAndOffset()[0],
            () => sortAndOffset()[1],
            () => sortAndOffset()[2],
            () => props.limit,
            () => props.queries,
          ),
          () => props.extraCellsBefore,
          () => props.extraCellsAfter,
          sortAndOffset,
          handleSort,
          paginatorComponent,
        )}
      />
    );
  };

// src/ui-react-dom/ResultSortedTableInHtmlTable.tsx
import type {
  HtmlTableProps,
  ResultSortedTableInHtmlTable as ResultSortedTableInHtmlTableDecl,
  ResultSortedTableInHtmlTableProps,
} from '../@types/ui-react-dom/index.js';
import {
  useResultRowCount,
  useResultSortedRowIds,
  useResultTableCellIds,
} from '../ui-react/hooks.ts';
import {ResultCellView} from '../ui-react/index.ts';
import {HtmlTable} from './common/components.tsx';
import {
  useCells,
  useParams,
  useQueriesCellComponentProps,
} from './common/hooks.tsx';
import {useSortingAndPagination} from './SortedTablePaginator.tsx';

export const ResultSortedTableInHtmlTable: typeof ResultSortedTableInHtmlTableDecl =
  ({
    queryId,
    cellId,
    descending,
    offset,
    limit,
    queries,
    sortOnClick,
    paginator = false,
    customCells,
    extraCellsBefore,
    extraCellsAfter,
    onChange,
    ...props
  }: ResultSortedTableInHtmlTableProps & HtmlTableProps): any => {
    const [sortAndOffset, handleSort, paginatorComponent] =
      useSortingAndPagination(
        cellId,
        descending,
        sortOnClick,
        offset,
        limit,
        useResultRowCount(queryId, queries),
        paginator,
        onChange,
      );
    return (
      <HtmlTable
        {...props}
        params={useParams(
          useCells(
            useResultTableCellIds(queryId, queries),
            customCells,
            ResultCellView,
          ),
          useQueriesCellComponentProps(queries, queryId),
          useResultSortedRowIds(queryId, ...sortAndOffset, limit, queries),
          extraCellsBefore,
          extraCellsAfter,
          sortAndOffset,
          handleSort,
          paginatorComponent,
        )}
      />
    );
  };
