// src/ui-svelte-dom/SliceInHtmlTable.svelte
<script lang="ts">
  import type {
    HtmlTableProps,
    SliceInHtmlTableProps,
  } from '../@types/ui-svelte-dom/index.d.ts';
  import {
    getIndexStoreTableId,
    getSliceRowIds,
    getTableCellIds,
  } from '../ui-svelte/functions.svelte.ts';
  import CellView from '../ui-svelte/CellView.svelte';
  import EditableCellView from './EditableCellView.svelte';
  import HtmlTable from './common/HtmlTable.svelte';
  import {getCells} from './common/index.ts';

  let {
    indexId,
    sliceId,
    indexes,
    editable,
    customCells,
    extraCellsBefore,
    extraCellsAfter,
    ...props
  }: SliceInHtmlTableProps & HtmlTableProps = $props();

  const index = getIndexStoreTableId(
    () => indexes,
    () => indexId,
  );
  const defaultCellIds = getTableCellIds(
    () => index.tableId as any,
    () => index.store,
  );
  const rowIds = getSliceRowIds(
    () => indexId,
    () => sliceId,
    () => indexes,
  );
  const defaultCellComponent = $derived(editable ? EditableCellView : CellView);
  const cells = $derived(
    getCells(defaultCellIds.current, customCells, defaultCellComponent),
  );
  const cellComponentProps = $derived({
    store: index.store,
    tableId: index.tableId as any,
  });
</script>

<HtmlTable
  {...props}
  {cells}
  {cellComponentProps}
  {rowIds}
  {extraCellsBefore}
  {extraCellsAfter}
/>

// src/ui-react-dom/SliceInHtmlTable.tsx
import type {Id} from '../@types/index.js';
import type {
  HtmlTableProps,
  SliceInHtmlTable as SliceInHtmlTableDecl,
  SliceInHtmlTableProps,
} from '../@types/ui-react-dom/index.js';
import {getIndexStoreTableId} from '../common/react.ts';
import {
  useIndexesOrIndexesById,
  useSliceRowIds,
  useTableCellIds,
} from '../ui-react/hooks.ts';
import {CellView} from '../ui-react/index.ts';
import {EditableCellView} from './EditableCellView.tsx';
import {
  HtmlTable,
  useCells,
  useParams,
  useStoreCellComponentProps,
} from './common.tsx';

export const SliceInHtmlTable: typeof SliceInHtmlTableDecl = ({
  indexId,
  sliceId,
  indexes,
  editable,
  customCells,
  extraCellsBefore,
  extraCellsAfter,
  ...props
}: SliceInHtmlTableProps & HtmlTableProps): any => {
  const [resolvedIndexes, store, tableId] = getIndexStoreTableId(
    useIndexesOrIndexesById(indexes),
    indexId,
  );
  return (
    <HtmlTable
      {...props}
      params={useParams(
        useCells(
          useTableCellIds(tableId as Id, store),
          customCells,
          editable ? EditableCellView : CellView,
        ),
        useStoreCellComponentProps(store, tableId as Id),
        useSliceRowIds(indexId, sliceId, resolvedIndexes),
        extraCellsBefore,
        extraCellsAfter,
      )}
    />
  );
};
