// src/ui-solid-dom/SortedTableInHtmlTable.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  HtmlTableProps,
  SortedTableInHtmlTable as SortedTableInHtmlTableDecl,
  SortedTableInHtmlTableProps,
} from '../@types/ui-solid-dom/index.d.ts';
import {CellView} from '../ui-solid/index.ts';
import {
  useRowCount,
  useSortedRowIds,
  useTableCellIds,
} from '../ui-solid/primitives.ts';
import {HtmlTable} from './common/components.tsx';
import {
  getParams,
  getStoreCellComponentProps,
  useCells,
} from './common/hooks.tsx';
import {EditableCellView} from './EditableCellView.tsx';
import {useSortingAndPagination} from './SortedTablePaginator.tsx';

export const SortedTableInHtmlTable: typeof SortedTableInHtmlTableDecl = (
  props: SortedTableInHtmlTableProps & HtmlTableProps,
): JSXElement => {
  const [sortAndOffset, handleSort, paginatorComponent] =
    useSortingAndPagination(
      () => props.cellId,
      () => props.descending,
      () => props.sortOnClick,
      () => props.offset,
      () => props.limit,
      useRowCount(
        () => props.tableId,
        () => props.store,
      ),
      () => props.paginator ?? false,
      () => props.onChange,
    );
  return (
    <HtmlTable
      {...props}
      params={getParams(
        useCells(
          useTableCellIds(
            () => props.tableId,
            () => props.store,
          ),
          props.customCells,
          props.editable ? EditableCellView : CellView,
        ),
        getStoreCellComponentProps(props.store, props.tableId),
        useSortedRowIds(
          () => props.tableId,
          () => sortAndOffset()[0],
          () => sortAndOffset()[1],
          () => sortAndOffset()[2],
          () => props.limit,
          () => props.store,
        ),
        props.extraCellsBefore,
        props.extraCellsAfter,
        sortAndOffset,
        handleSort,
        paginatorComponent,
      )}
    />
  );
};

// src/ui-react-dom/SortedTableInHtmlTable.tsx
import type {
  HtmlTableProps,
  SortedTableInHtmlTable as SortedTableInHtmlTableDecl,
  SortedTableInHtmlTableProps,
} from '../@types/ui-react-dom/index.js';
import {
  useRowCount,
  useSortedRowIds,
  useTableCellIds,
} from '../ui-react/hooks.ts';
import {CellView} from '../ui-react/index.ts';
import {HtmlTable} from './common/components.tsx';
import {
  useCells,
  useParams,
  useStoreCellComponentProps,
} from './common/hooks.tsx';
import {EditableCellView} from './EditableCellView.tsx';
import {useSortingAndPagination} from './SortedTablePaginator.tsx';

export const SortedTableInHtmlTable: typeof SortedTableInHtmlTableDecl = ({
  tableId,
  cellId,
  descending,
  offset,
  limit,
  store,
  editable,
  sortOnClick,
  paginator = false,
  onChange,
  customCells,
  extraCellsBefore,
  extraCellsAfter,
  ...props
}: SortedTableInHtmlTableProps & HtmlTableProps): any => {
  const [sortAndOffset, handleSort, paginatorComponent] =
    useSortingAndPagination(
      cellId,
      descending,
      sortOnClick,
      offset,
      limit,
      useRowCount(tableId, store),
      paginator,
      onChange,
    );
  return (
    <HtmlTable
      {...props}
      params={useParams(
        useCells(
          useTableCellIds(tableId, store),
          customCells,
          editable ? EditableCellView : CellView,
        ),
        useStoreCellComponentProps(store, tableId),
        useSortedRowIds(tableId, ...sortAndOffset, limit, store),
        extraCellsBefore,
        extraCellsAfter,
        sortAndOffset,
        handleSort,
        paginatorComponent,
      )}
    />
  );
};
