// src/ui-solid-dom/TableInHtmlTable.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  HtmlTableProps,
  TableInHtmlTable as TableInHtmlTableDecl,
  TableInHtmlTableProps,
} from '../@types/ui-solid-dom/index.d.ts';
import {CellView} from '../ui-solid/index.ts';
import {useRowIds, useTableCellIds} from '../ui-solid/primitives.ts';
import {HtmlTable} from './common/components.tsx';
import {
  getParams,
  getStoreCellComponentProps,
  useCells,
} from './common/hooks.tsx';
import {EditableCellView} from './EditableCellView.tsx';

export const TableInHtmlTable: typeof TableInHtmlTableDecl = (
  props: TableInHtmlTableProps & HtmlTableProps,
): JSXElement => (
  <HtmlTable
    {...props}
    params={getParams(
      useCells(
        useTableCellIds(
          () => props.tableId,
          () => props.store,
        ),
        () => props.customCells,
        () => (props.editable ? EditableCellView : CellView),
      ),
      getStoreCellComponentProps(
        () => props.store,
        () => props.tableId,
      ),
      useRowIds(
        () => props.tableId,
        () => props.store,
      ),
      () => props.extraCellsBefore,
      () => props.extraCellsAfter,
    )}
  />
);

// src/ui-react-dom/TableInHtmlTable.tsx
import type {
  HtmlTableProps,
  TableInHtmlTable as TableInHtmlTableDecl,
  TableInHtmlTableProps,
} from '../@types/ui-react-dom/index.d.ts';
import {useRowIds, useTableCellIds} from '../ui-react/hooks.ts';
import {CellView} from '../ui-react/index.ts';
import {HtmlTable} from './common/components.tsx';
import {
  useCells,
  useParams,
  useStoreCellComponentProps,
} from './common/hooks.tsx';
import {EditableCellView} from './EditableCellView.tsx';

export const TableInHtmlTable: typeof TableInHtmlTableDecl = ({
  tableId,
  store,
  editable,
  customCells,
  extraCellsBefore,
  extraCellsAfter,
  ...props
}: TableInHtmlTableProps & HtmlTableProps): any => (
  <HtmlTable
    {...props}
    params={useParams(
      useCells(
        useTableCellIds(tableId, store),
        customCells,
        editable ? EditableCellView : CellView,
      ),
      useStoreCellComponentProps(store, tableId),
      useRowIds(tableId, store),
      extraCellsBefore,
      extraCellsAfter,
    )}
  />
);
