// src/ui-svelte-dom/TableInHtmlTable.svelte
<script lang="ts">
  import type {
    HtmlTableProps,
    TableInHtmlTableProps,
  } from '../@types/ui-svelte-dom/index.d.ts';
  import {getRowIds, getTableCellIds} from '../ui-svelte/functions.svelte.ts';
  import CellView from '../ui-svelte/CellView.svelte';
  import EditableCellView from './EditableCellView.svelte';
  import HtmlTable from './common/HtmlTable.svelte';
  import {getCells} from './common/index.ts';

  let {
    tableId,
    store,
    editable,
    customCells,
    extraCellsBefore,
    extraCellsAfter,
    ...props
  }: TableInHtmlTableProps & HtmlTableProps = $props();

  const defaultCellIds = getTableCellIds(
    () => tableId,
    () => store,
  );
  const rowIds = getRowIds(
    () => tableId,
    () => store,
  );
  const defaultCellComponent = $derived(editable ? EditableCellView : CellView);
  const cells = $derived(
    getCells(defaultCellIds.current, customCells, defaultCellComponent),
  );
  const cellComponentProps = $derived({store, tableId});
</script>

<HtmlTable
  {...props}
  {cells}
  {cellComponentProps}
  {rowIds}
  {extraCellsBefore}
  {extraCellsAfter}
/>

// src/ui-react-dom/TableInHtmlTable.tsx
import type {
  HtmlTableProps,
  TableInHtmlTable as TableInHtmlTableDecl,
  TableInHtmlTableProps,
} from '../@types/ui-react-dom/index.js';
import {useRowIds, useTableCellIds} from '../ui-react/hooks.ts';
import {CellView} from '../ui-react/index.ts';
import {EditableCellView} from './EditableCellView.tsx';
import {
  HtmlTable,
  useCells,
  useParams,
  useStoreCellComponentProps,
} from './common.tsx';

export const TableInHtmlTable: typeof TableInHtmlTableDecl = ({
  tableId,
  store,
  editable,
  customCells,
  extraCellsBefore,
  extraCellsAfter,
  ...props
}: TableInHtmlTableProps & HtmlTableProps): any => (
  <HtmlTable
    {...props}
    params={useParams(
      useCells(
        useTableCellIds(tableId, store),
        customCells,
        editable ? EditableCellView : CellView,
      ),
      useStoreCellComponentProps(store, tableId),
      useRowIds(tableId, store),
      extraCellsBefore,
      extraCellsAfter,
    )}
  />
);
