// src/ui-solid-dom/ValuesInHtmlTable.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  ExtraValueCell,
  HtmlTableProps,
  ValuesInHtmlTable as ValuesInHtmlTableDecl,
  ValuesInHtmlTableProps,
} from '../@types/ui-solid-dom/index.d.ts';
import type {ValueProps} from '../@types/ui-solid/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {isFalse} from '../common/other.ts';
import {getProps, getValue} from '../common/solid.ts';
import {EXTRA, VALUE} from '../common/strings.ts';
import {ValueView} from '../ui-solid/index.ts';
import {useValueIds} from '../ui-solid/primitives.ts';
import {EditableValueView} from './EditableValueView.tsx';
import {extraHeaders} from './common/index.tsx';

const extraValueCells = (
  extraValueCells: ExtraValueCell[] | (() => ExtraValueCell[] | undefined) = [],
  extraValueCellProps: ValueProps,
) =>
  arrayMap(getValue(extraValueCells) ?? [], (extraValueCell) => {
    const Component = extraValueCell.component;
    return (
      <td class={EXTRA}>
        <Component {...extraValueCellProps} />
      </td>
    );
  });

export const ValuesInHtmlTable: typeof ValuesInHtmlTableDecl = (
  props: ValuesInHtmlTableProps & HtmlTableProps,
): JSXElement => {
  const valueIds = useValueIds(() => props.store);
  return (
    <table class={props.className}>
      {props.headerRow === false ? null : (
        <thead>
          <tr>
            {extraHeaders(props.extraCellsBefore as any)}
            {props.idColumn === false ? null : <th>Id</th>}
            <th>{VALUE}</th>
            {extraHeaders(props.extraCellsAfter as any)}
          </tr>
        </thead>
      )}
      <tbody>
        {arrayMap(valueIds(), (valueId) => {
          const valueProps = {valueId, store: props.store};
          const Value =
            props.valueComponent ??
            (getValue(props.editable as any) === true
              ? EditableValueView
              : ValueView);
          return (
            <tr>
              {extraValueCells(props.extraCellsBefore as any, valueProps)}
              {isFalse(props.idColumn) ? null : (
                <th title={valueId}>{valueId}</th>
              )}
              <td>
                <Value
                  {...getProps(props.getValueComponentProps, valueId)}
                  {...valueProps}
                />
              </td>
              {extraValueCells(props.extraCellsAfter as any, valueProps)}
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};

// src/ui-react-dom/ValuesInHtmlTable.tsx
import type {
  ExtraValueCell,
  HtmlTableProps,
  ValuesInHtmlTable as ValuesInHtmlTableDecl,
  ValuesInHtmlTableProps,
} from '../@types/ui-react-dom/index.d.ts';
import type {ValueProps} from '../@types/ui-react/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {isFalse} from '../common/other.ts';
import {getProps} from '../common/react.ts';
import {EXTRA, VALUE} from '../common/strings.ts';
import {useValueIds} from '../ui-react/hooks.ts';
import {ValueView} from '../ui-react/index.ts';
import {EditableValueView} from './EditableValueView.tsx';
import {extraHeaders, extraKey} from './common/index.tsx';

const extraValueCells = (
  extraValueCells: ExtraValueCell[] = [],
  extraValueCellProps: ValueProps,
  after: 0 | 1 = 0,
) =>
  arrayMap(extraValueCells, ({component: Component}, index) => (
    <td className={EXTRA} key={extraKey(index, after)}>
      <Component {...extraValueCellProps} />
    </td>
  ));

export const ValuesInHtmlTable: typeof ValuesInHtmlTableDecl = ({
  store,
  editable = false,
  valueComponent: Value = editable ? EditableValueView : ValueView,
  getValueComponentProps,
  extraCellsBefore,
  extraCellsAfter,
  className,
  headerRow,
  idColumn,
}: ValuesInHtmlTableProps & HtmlTableProps): any => (
  <table className={className}>
    {headerRow === false ? null : (
      <thead>
        <tr>
          {extraHeaders(extraCellsBefore)}
          {idColumn === false ? null : <th>Id</th>}
          <th>{VALUE}</th>
          {extraHeaders(extraCellsAfter, 1)}
        </tr>
      </thead>
    )}
    <tbody>
      {arrayMap(useValueIds(store), (valueId) => {
        const valueProps = {valueId, store};
        return (
          <tr key={valueId}>
            {extraValueCells(extraCellsBefore, valueProps)}
            {isFalse(idColumn) ? null : <th title={valueId}>{valueId}</th>}
            <td>
              <Value
                {...getProps(getValueComponentProps, valueId)}
                {...valueProps}
              />
            </td>
            {extraValueCells(extraCellsAfter, valueProps, 1)}
          </tr>
        );
      })}
    </tbody>
  </table>
);
