// src/ui-react/CheckpointView.tsx
import type {
  CheckpointProps,
  CheckpointView as CheckpointViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useCheckpoint} from './hooks.ts';

export const CheckpointView: typeof CheckpointViewDecl = ({
  checkpoints,
  checkpointId,
  debugIds,
}: CheckpointProps): any => (
  <Wrap debugIds={debugIds} id={checkpointId}>
    {useCheckpoint(checkpointId, checkpoints) ?? EMPTY_STRING}
  </Wrap>
);

// src/ui-solid/CheckpointView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  CheckpointProps,
} from '../@types/ui-solid/index.d.ts';
import {getValue} from '../common/solid.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useCheckpoint} from './hooks.ts';

export const CheckpointView = (props: CheckpointProps): JSXElement => {
  const checkpoint = useCheckpoint(
    () => props.checkpointId,
    () => props.checkpoints,
  );
  return renderView(() =>
    wrap(
      getValue(checkpoint) ?? EMPTY_STRING,
      undefined,
      props.debugIds,
      props.checkpointId,
    ),
  );
};
