// src/ui-react/IndexView.tsx
import type {
  IndexProps,
  IndexView as IndexViewDecl,
} from '../@types/ui-react/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps} from '../common/react.ts';
import {Wrap} from './common/Wrap.tsx';
import {useSliceIds} from './hooks.ts';
import {SliceView} from './SliceView.tsx';

export const IndexView: typeof IndexViewDecl = ({
  indexId,
  indexes,
  sliceComponent: Slice = SliceView,
  getSliceComponentProps,
  separator,
  debugIds,
}: IndexProps): any => (
  <Wrap separator={separator} debugIds={debugIds} id={indexId}>
    {arrayMap(useSliceIds(indexId, indexes), (sliceId) => (
      <Slice
        key={sliceId}
        {...getProps(getSliceComponentProps, sliceId)}
        indexId={indexId}
        sliceId={sliceId}
        indexes={indexes}
        debugIds={debugIds}
      />
    ))}
  </Wrap>
);

// src/ui-solid/IndexView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  IndexProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useSliceIds} from './hooks.ts';
import {SliceView} from './SliceView.tsx';

export const IndexView = (props: IndexProps): JSXElement => {
  const sliceIds = useSliceIds(
    () => props.indexId,
    () => props.indexes,
  );
  return renderView(() => {
    const Slice = props.sliceComponent ?? SliceView;
    return wrap(
      arrayMap(getValue(sliceIds) as Id[], (sliceId: Id) => (
        <Slice
          {...getProps(props.getSliceComponentProps, sliceId)}
          indexId={props.indexId}
          sliceId={sliceId}
          indexes={props.indexes}
          debugIds={props.debugIds}
        />
      )),
      props.separator,
      props.debugIds,
      props.indexId,
    );
  });
};
