// src/ui-react/MetricView.tsx
import type {
  MetricProps,
  MetricView as MetricViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useMetric} from './hooks.ts';

export const MetricView: typeof MetricViewDecl = ({
  metricId,
  metrics,
  debugIds,
}: MetricProps): any => (
  <Wrap debugIds={debugIds} id={metricId}>
    {useMetric(metricId, metrics) ?? EMPTY_STRING}
  </Wrap>
);

// src/ui-solid/MetricView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  MetricProps,
} from '../@types/ui-solid/index.d.ts';
import {getValue} from '../common/solid.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useMetric} from './hooks.ts';

export const MetricView = (props: MetricProps): JSXElement => {
  const metric = useMetric(
    () => props.metricId,
    () => props.metrics,
  );
  return renderView(() =>
    wrap(
      getValue(metric) ?? EMPTY_STRING,
      undefined,
      props.debugIds,
      props.metricId,
    ),
  );
};
