// src/ui-react/ResultCellView.tsx
import type {
  ResultCellProps,
  ResultCellView as ResultCellViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useResultCell} from './hooks.ts';

export const ResultCellView: typeof ResultCellViewDecl = ({
  queryId,
  rowId,
  cellId,
  queries,
  debugIds,
}: ResultCellProps): any => (
  <Wrap debugIds={debugIds} id={cellId}>
    {EMPTY_STRING +
      (useResultCell(queryId, rowId, cellId, queries) ?? EMPTY_STRING)}
  </Wrap>
);

// src/ui-solid/ResultCellView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  ResultCellProps,
} from '../@types/ui-solid/index.d.ts';
import {getValue} from '../common/solid.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useResultCell} from './hooks.ts';

export const ResultCellView = (props: ResultCellProps): JSXElement => {
  const resultCell = useResultCell(
    () => props.queryId,
    () => props.rowId,
    () => props.cellId,
    () => props.queries,
  );
  return renderView(() =>
    wrap(
      EMPTY_STRING + (getValue(resultCell) ?? EMPTY_STRING),
      undefined,
      props.debugIds,
      props.cellId,
    ),
  );
};
