// src/ui-react/SliceView.tsx
import type {Id} from '../@types/index.d.ts';
import type {
  SliceProps,
  SliceView as SliceViewDecl,
} from '../@types/ui-react/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getIndexStoreTableId, getProps} from '../common/react.ts';
import {Wrap} from './common/Wrap.tsx';
import {useIndexesOrIndexesById, useSliceRowIds} from './hooks.ts';
import {RowView} from './RowView.tsx';

export const SliceView: typeof SliceViewDecl = ({
  indexId,
  sliceId,
  indexes,
  rowComponent: Row = RowView,
  getRowComponentProps,
  separator,
  debugIds,
}: SliceProps): any => {
  const [resolvedIndexes, store, tableId] = getIndexStoreTableId(
    useIndexesOrIndexesById(indexes),
    indexId,
  );
  const rowIds = useSliceRowIds(indexId, sliceId, resolvedIndexes);
  return (
    <Wrap separator={separator} debugIds={debugIds} id={sliceId}>
      {arrayMap(rowIds, (rowId) => (
        <Row
          key={rowId}
          {...getProps(getRowComponentProps, rowId)}
          tableId={tableId as Id}
          rowId={rowId}
          store={store}
          debugIds={debugIds}
        />
      ))}
    </Wrap>
  );
};

// src/ui-solid/SliceView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {Id} from '../@types/index.d.ts';
import type {
  SliceProps,
} from '../@types/ui-solid/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getIndexStoreTableId, getProps, getValue} from '../common/solid.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useIndexesOrIndexesById, useSliceRowIds} from './hooks.ts';
import {RowView} from './RowView.tsx';

export const SliceView = (props: SliceProps): JSXElement => {
  const resolvedIndexes = useIndexesOrIndexesById(
    () => props.indexes,
  );
  const rowIds = useSliceRowIds(
    () => props.indexId,
    () => props.sliceId,
    resolvedIndexes,
  );
  return renderView(() => {
    const Row = props.rowComponent ?? RowView;
    const [_indexesValue, store, tableId] = getIndexStoreTableId(
      getValue(resolvedIndexes),
      props.indexId,
    );
    return wrap(
      arrayMap(getValue(rowIds) as Id[], (rowId) => (
        <Row
          {...getProps(props.getRowComponentProps, rowId)}
          tableId={tableId as Id}
          rowId={rowId}
          store={store}
          debugIds={props.debugIds}
        />
      )),
      props.separator,
      props.debugIds,
      props.sliceId,
    );
  });
};
