// src/ui-svelte/SortedTableView.svelte
<script lang="ts">
  import type {SortedTableViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useSortedRowIds} from './hooks.svelte.ts';
  import RowView from './RowView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {
    tableId,
    cellId,
    descending,
    offset,
    limit,
    store,
    customCellIds,
    separator,
    debugIds,
    row,
  }: SortedTableViewProps = $props();

  const rowIds = useSortedRowIds(
    () => tableId,
    () => cellId,
    () => descending ?? false,
    () => offset ?? 0,
    () => limit,
    () => store,
  );
</script>

<Wrap
  ids={rowIds.current}
  {separator}
  {debugIds}
  id={tableId}
  custom={row}
>
  {#snippet children(rowId)}
    <RowView {tableId} {rowId} {store} {customCellIds} {debugIds} />
  {/snippet}
</Wrap>

// src/ui-solid/SortedTableView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  SortedTableProps,
} from '../@types/ui-solid/index.d.ts';
import {tableView} from './common/index.tsx';
import {useSortedRowIds} from './hooks.ts';

export const SortedTableView = (props: SortedTableProps): JSXElement =>
  tableView(
    props,
    useSortedRowIds(
      () => props.tableId,
      () => props.cellId,
      () => props.descending,
      () => props.offset,
      () => props.limit,
      () => props.store,
    ),
  );
