// src/ui-react/TablesView.tsx
import type {
  TablesProps,
  TablesView as TablesViewDecl,
} from '../@types/ui-react/index.js';
import {arrayMap} from '../common/array.ts';
import {getProps} from '../common/react.ts';
import {wrap} from './common/wrap.tsx';
import {useTableIds} from './hooks.ts';
import {TableView} from './TableView.tsx';

export const TablesView: typeof TablesViewDecl = ({
  store,
  tableComponent: Table = TableView,
  getTableComponentProps,
  separator,
  debugIds,
}: TablesProps): any =>
  wrap(
    arrayMap(useTableIds(store), (tableId) => (
      <Table
        key={tableId}
        {...getProps(getTableComponentProps, tableId)}
        tableId={tableId}
        store={store}
        debugIds={debugIds}
      />
    )),
    separator,
  );

// src/ui-solid/TablesView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  TablesProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useTableIds} from './hooks.ts';
import {TableView} from './TableView.tsx';

export const TablesView = (props: TablesProps): JSXElement => {
  const tableIds = useTableIds(() => props.store);
  return renderView(() => {
    const Table = props.tableComponent ?? TableView;
    return wrap(
      arrayMap(getValue(tableIds) as Id[], (tableId: Id) => (
        <Table
          {...getProps(props.getTableComponentProps, tableId)}
          tableId={tableId}
          store={props.store}
          debugIds={props.debugIds}
        />
      )),
      props.separator,
    );
  });
};
