// src/ui-svelte/TableView.svelte
<script lang="ts">
  import type {TableViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useRowIds} from './hooks.svelte.ts';
  import RowView from './RowView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {
    tableId,
    store,
    customCellIds,
    separator,
    debugIds,
    row,
  }: TableViewProps = $props();

  const rowIds = useRowIds(
    () => tableId,
    () => store,
  );
</script>

<Wrap
  ids={rowIds.current}
  {separator}
  {debugIds}
  id={tableId}
  custom={row}
>
  {#snippet children(rowId)}
    <RowView {tableId} {rowId} {store} {customCellIds} {debugIds} />
  {/snippet}
</Wrap>

// src/ui-solid/TableView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  TableProps,
} from '../@types/ui-solid/index.d.ts';
import {tableView} from './common/index.tsx';
import {useRowIds} from './hooks.ts';

export const TableView = (props: TableProps): JSXElement =>
  tableView(
    props,
    useRowIds(() => props.tableId, () => props.store),
  );
