// src/ui-svelte/ValuesView.svelte
<script lang="ts">
  import type {ValuesViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useValueIds} from './hooks.svelte.ts';
  import ValueView from './ValueView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {store, separator, debugIds, value}: ValuesViewProps = $props();
  const valueIds = useValueIds(() => store);
</script>

<Wrap ids={valueIds.current} {separator} {debugIds} custom={value}>
  {#snippet children(valueId)}
    <ValueView {valueId} {store} {debugIds} />
  {/snippet}
</Wrap>

// src/ui-solid/ValuesView.tsx
/* @jsxImportSource solid-js */
import type {
  ValuesProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {wrap} from './common/wrap.tsx';
import {useValueIds} from './hooks.ts';
import {ValueView} from './ValueView.tsx';

export const ValuesView = (props: ValuesProps): any => {
  const valueIds = useValueIds((() => props.store) as any) as any;
  return () => {
    const Value = props.valueComponent ?? ValueView;
    return wrap(
      arrayMap(getValue(valueIds) as Id[], (valueId: Id) => (
        <Value
          {...getProps(props.getValueComponentProps, valueId)}
          valueId={valueId}
          store={props.store}
          debugIds={props.debugIds}
        />
      )),
      props.separator,
    );
  };
};
