// src/ui-react/CheckpointView.tsx
import type {
  CheckpointProps,
  CheckpointView as CheckpointViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useCheckpoint} from './hooks.ts';

export const CheckpointView: typeof CheckpointViewDecl = ({
  checkpoints,
  checkpointId,
  debugIds,
}: CheckpointProps): any => (
  <Wrap debugIds={debugIds} id={checkpointId}>
    {useCheckpoint(checkpointId, checkpoints) ?? EMPTY_STRING}
  </Wrap>
);

// src/ui-svelte/CheckpointView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import type {Checkpoints} from '../@types/checkpoints/index.d.ts';
  import {useCheckpoint} from './hooks.svelte.ts';

  type Props = {
    checkpointId: Id;
    checkpoints?: Checkpoints | Id;
    debugIds?: boolean;
  };

  let {checkpointId, checkpoints, debugIds}: Props = $props();
  const checkpoint = useCheckpoint(
    () => checkpointId,
    () => checkpoints,
  );
  const display = $derived('' + (checkpoint.current ?? ''));
  const output = $derived(debugIds ? `${checkpointId}:{${display}}` : display);
</script>

{output}
