// src/ui-solid/IndexView.tsx
/* @jsxImportSource solid-js */
import type {
  IndexProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {wrap} from './common/wrap.tsx';
import {useSliceIds} from './hooks.ts';
import {SliceView} from './SliceView.tsx';

export const IndexView = ({
  indexId,
  indexes,
  sliceComponent: Slice = SliceView,
  getSliceComponentProps,
  separator,
  debugIds,
}: IndexProps): any => {
  const sliceIds = useSliceIds(indexId, indexes) as any;
  return () =>
    wrap(
      arrayMap(getValue(sliceIds) as Id[], (sliceId: Id) => (
        <Slice
          {...getProps(getSliceComponentProps, sliceId)}
          indexId={indexId}
          sliceId={sliceId}
          indexes={indexes}
          debugIds={debugIds}
        />
      )),
      separator,
      debugIds,
      indexId,
    );
};

// src/ui-svelte/IndexView.svelte
<script lang="ts">
  import type {IndexViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useSliceIds} from './hooks.svelte.ts';
  import SliceView from './SliceView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {indexId, indexes, separator, debugIds, slice}: IndexViewProps = $props();
  const sliceIds = useSliceIds(
    () => indexId,
    () => indexes,
  );
</script>

<Wrap
  ids={sliceIds.current}
  {separator}
  {debugIds}
  id={indexId}
  custom={slice}
>
  {#snippet children(sliceId)}
    <SliceView {indexId} {sliceId} {indexes} {debugIds} />
  {/snippet}
</Wrap>
