// src/ui-react/ResultCellView.tsx
import type {
  ResultCellProps,
  ResultCellView as ResultCellViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useResultCell} from './hooks.ts';

export const ResultCellView: typeof ResultCellViewDecl = ({
  queryId,
  rowId,
  cellId,
  queries,
  debugIds,
}: ResultCellProps): any => (
  <Wrap debugIds={debugIds} id={cellId}>
    {EMPTY_STRING +
      (useResultCell(queryId, rowId, cellId, queries) ?? EMPTY_STRING)}
  </Wrap>
);

// src/ui-svelte/ResultCellView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import type {Queries} from '../@types/queries/index.d.ts';
  import {useResultCell} from './hooks.svelte.ts';

  type Props = {
    queryId: Id;
    rowId: Id;
    cellId: Id;
    queries?: Queries | Id;
    debugIds?: boolean;
  };

  let {queryId, rowId, cellId, queries, debugIds}: Props = $props();
  const cell = useResultCell(
    () => queryId,
    () => rowId,
    () => cellId,
    () => queries,
  );
  const display = $derived('' + (cell.current ?? ''));
  const output = $derived(debugIds ? `${cellId}:{${display}}` : display);
</script>

{output}
