// src/ui-react/ResultRowView.tsx
import type {
  ResultRowProps,
  ResultRowView as ResultRowViewDecl,
} from '../@types/ui-react/index.js';
import {arrayMap} from '../common/array.ts';
import {getProps} from '../common/react.ts';
import {wrap} from './common.tsx';
import {useResultCellIds} from './hooks.ts';
import {ResultCellView} from './ResultCellView.tsx';

export const ResultRowView: typeof ResultRowViewDecl = ({
  queryId,
  rowId,
  queries,
  resultCellComponent: ResultCell = ResultCellView,
  getResultCellComponentProps,
  separator,
  debugIds,
}: ResultRowProps): any =>
  wrap(
    arrayMap(useResultCellIds(queryId, rowId, queries), (cellId) => (
      <ResultCell
        key={cellId}
        {...getProps(getResultCellComponentProps, cellId)}
        queryId={queryId}
        rowId={rowId}
        cellId={cellId}
        queries={queries}
        debugIds={debugIds}
      />
    )),
    separator,
    debugIds,
    rowId,
  );

// src/ui-svelte/ResultRowView.svelte
<script lang="ts">
  import type {ResultRowViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useResultCellIds} from './hooks.svelte.ts';
  import ResultCellView from './ResultCellView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {queryId, rowId, queries, separator, debugIds, cell}: ResultRowViewProps =
    $props();
  const cellIds = useResultCellIds(
    () => queryId,
    () => rowId,
    () => queries,
  );
</script>

<Wrap
  ids={cellIds.current}
  {separator}
  {debugIds}
  id={rowId}
  custom={cell}
>
  {#snippet children(cellId)}
    <ResultCellView {queryId} {rowId} {cellId} {queries} {debugIds} />
  {/snippet}
</Wrap>
