// src/ui-react/RowView.tsx
import type {
  RowProps,
  RowView as RowViewDecl,
} from '../@types/ui-react/index.js';
import {arrayMap} from '../common/array.ts';
import {getProps} from '../common/react.ts';
import {CellView} from './CellView.tsx';
import {useCustomOrDefaultCellIds} from './common/hooks.tsx';
import {wrap} from './common/wrap.tsx';

export const RowView: typeof RowViewDecl = ({
  tableId,
  rowId,
  store,
  cellComponent: Cell = CellView,
  getCellComponentProps,
  customCellIds,
  separator,
  debugIds,
}: RowProps): any =>
  wrap(
    arrayMap(
      useCustomOrDefaultCellIds(customCellIds, tableId, rowId, store),
      (cellId) => (
        <Cell
          key={cellId}
          {...getProps(getCellComponentProps, cellId)}
          tableId={tableId}
          rowId={rowId}
          cellId={cellId}
          store={store}
          debugIds={debugIds}
        />
      ),
    ),
    separator,
    debugIds,
    rowId,
  );

// src/ui-svelte/RowView.svelte
<script lang="ts">
  import type {RowViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useCellIds} from './hooks.svelte.ts';
  import CellView from './CellView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {
    tableId,
    rowId,
    store,
    customCellIds,
    separator,
    debugIds,
    cell,
  }: RowViewProps = $props();

  const defaultCellIds = useCellIds(
    () => tableId,
    () => rowId,
    () => store,
  );
  const activeCellIds = $derived(customCellIds ?? defaultCellIds.current);
</script>

<Wrap ids={activeCellIds} {separator} {debugIds} id={rowId} custom={cell}>
  {#snippet children(cellId)}
    <CellView {tableId} {rowId} {cellId} {store} {debugIds} />
  {/snippet}
</Wrap>
