// src/ui-solid/TablesView.tsx
/* @jsxImportSource solid-js */
import type {
  TablesProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {wrap} from './common/wrap.tsx';
import {useTableIds} from './hooks.ts';
import {TableView} from './TableView.tsx';

export const TablesView = ({
  store,
  tableComponent: Table = TableView,
  getTableComponentProps,
  separator,
  debugIds,
}: TablesProps): any => {
  const tableIds = useTableIds(store) as any;
  return () =>
    wrap(
      arrayMap(getValue(tableIds) as Id[], (tableId: Id) => (
        <Table
          {...getProps(getTableComponentProps, tableId)}
          tableId={tableId}
          store={store}
          debugIds={debugIds}
        />
      )),
      separator,
    );
};

// src/ui-svelte/TablesView.svelte
<script lang="ts">
  import type {TablesViewProps} from '../@types/ui-svelte/index.d.ts';
  import {useTableIds} from './hooks.svelte.ts';
  import TableView from './TableView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {store, separator, debugIds, table}: TablesViewProps = $props();
  const tableIds = useTableIds(() => store);
</script>

<Wrap ids={tableIds.current} {separator} {debugIds} custom={table}>
  {#snippet children(tableId)}
    <TableView {tableId} {store} {debugIds} />
  {/snippet}
</Wrap>
