// src/ui-react/ValueView.tsx
import type {
  ValueProps,
  ValueView as ValueViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useValue} from './hooks.ts';

export const ValueView: typeof ValueViewDecl = ({
  valueId,
  store,
  debugIds,
}: ValueProps): any => (
  <Wrap debugIds={debugIds} id={valueId}>
    {EMPTY_STRING + (useValue(valueId, store) ?? EMPTY_STRING)}
  </Wrap>
);

// src/ui-svelte/ValueView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import type {Store} from '../@types/store/index.d.ts';
  import {useValue} from './hooks.svelte.ts';

  type Props = {
    valueId: Id;
    store?: Store | Id;
    debugIds?: boolean;
  };

  let {valueId, store, debugIds}: Props = $props();
  const value = useValue(
    () => valueId,
    () => store,
  );
  const display = $derived('' + (value.current ?? ''));
  const output = $derived(debugIds ? `${valueId}:{${display}}` : display);
</script>

{output}
