// src/ui-svelte/CellView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import type {Store} from '../@types/store/index.d.ts';
  import {useCell} from './hooks.svelte.ts';

  type Props = {
    tableId: Id;
    rowId: Id;
    cellId: Id;
    store?: Store | Id;
    debugIds?: boolean;
  };

  let {tableId, rowId, cellId, store, debugIds}: Props = $props();
  const cell = useCell(
    () => tableId,
    () => rowId,
    () => cellId,
    () => store,
  );
  const display = $derived('' + (cell.current ?? ''));
  const output = $derived(debugIds ? `${cellId}:{${display}}` : display);
</script>

{output}

// src/ui-react/CellView.tsx
import type {
  CellProps,
  CellView as CellViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useCell} from './hooks.ts';

export const CellView: typeof CellViewDecl = ({
  tableId,
  rowId,
  cellId,
  store,
  debugIds,
}: CellProps): any => (
  <Wrap debugIds={debugIds} id={cellId}>
    {EMPTY_STRING + (useCell(tableId, rowId, cellId, store) ?? EMPTY_STRING)}
  </Wrap>
);
