// src/ui-solid/CellView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  CellProps,
} from '../@types/ui-solid/index.d.ts';
import {getValue} from '../common/solid.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useCell} from './hooks.ts';

export const CellView = (props: CellProps): JSXElement => {
  const cell = useCell(
    () => props.tableId,
    () => props.rowId,
    () => props.cellId,
    () => props.store,
  );
  return renderView(() =>
    wrap(
      EMPTY_STRING + (getValue(cell) ?? EMPTY_STRING),
      undefined,
      props.debugIds,
      props.cellId,
    ),
  );
};

// src/ui-react/CellView.tsx
import type {
  CellProps,
  CellView as CellViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useCell} from './hooks.ts';

export const CellView: typeof CellViewDecl = ({
  tableId,
  rowId,
  cellId,
  store,
  debugIds,
}: CellProps): any => (
  <Wrap debugIds={debugIds} id={cellId}>
    {EMPTY_STRING + (useCell(tableId, rowId, cellId, store) ?? EMPTY_STRING)}
  </Wrap>
);
