// src/ui-svelte/MetricView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import type {Metrics} from '../@types/metrics/index.d.ts';
  import {useMetric} from './hooks.svelte.ts';

  type Props = {
    metricId: Id;
    metrics?: Metrics | Id;
    debugIds?: boolean;
  };

  let {metricId, metrics, debugIds}: Props = $props();
  const metric = useMetric(
    () => metricId,
    () => metrics,
  );
  const display = $derived('' + (metric.current ?? ''));
  const output = $derived(debugIds ? `${metricId}:{${display}}` : display);
</script>

{output}

// src/ui-react/MetricView.tsx
import type {
  MetricProps,
  MetricView as MetricViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useMetric} from './hooks.ts';

export const MetricView: typeof MetricViewDecl = ({
  metricId,
  metrics,
  debugIds,
}: MetricProps): any => (
  <Wrap debugIds={debugIds} id={metricId}>
    {useMetric(metricId, metrics) ?? EMPTY_STRING}
  </Wrap>
);
