// src/ui-solid/ResultRowView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  ResultRowProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useResultCellIds} from './hooks.ts';
import {ResultCellView} from './ResultCellView.tsx';

export const ResultRowView = (props: ResultRowProps): JSXElement => {
  const resultCellIds = useResultCellIds(
    () => props.queryId,
    () => props.rowId,
    () => props.queries,
  );
  return renderView(() => {
    const ResultCell = props.resultCellComponent ?? ResultCellView;
    return wrap(
      arrayMap(getValue(resultCellIds) as Id[], (cellId: Id) => (
        <ResultCell
          {...getProps(props.getResultCellComponentProps, cellId)}
          queryId={props.queryId}
          rowId={props.rowId}
          cellId={cellId}
          queries={props.queries}
          debugIds={props.debugIds}
        />
      )),
      props.separator,
      props.debugIds,
      props.rowId,
    );
  });
};

// src/ui-react/ResultRowView.tsx
import type {
  ResultRowProps,
  ResultRowView as ResultRowViewDecl,
} from '../@types/ui-react/index.js';
import {arrayMap} from '../common/array.ts';
import {getProps} from '../common/react.ts';
import {wrap} from './common.tsx';
import {useResultCellIds} from './hooks.ts';
import {ResultCellView} from './ResultCellView.tsx';

export const ResultRowView: typeof ResultRowViewDecl = ({
  queryId,
  rowId,
  queries,
  resultCellComponent: ResultCell = ResultCellView,
  getResultCellComponentProps,
  separator,
  debugIds,
}: ResultRowProps): any =>
  wrap(
    arrayMap(useResultCellIds(queryId, rowId, queries), (cellId) => (
      <ResultCell
        key={cellId}
        {...getProps(getResultCellComponentProps, cellId)}
        queryId={queryId}
        rowId={rowId}
        cellId={cellId}
        queries={queries}
        debugIds={debugIds}
      />
    )),
    separator,
    debugIds,
    rowId,
  );
