// src/ui-svelte/SliceView.svelte
<script lang="ts">
  import type {SliceViewProps} from '../@types/ui-svelte/index.d.ts';
  import {getIndexStoreTableId, createSliceRowIds} from './hooks.svelte.ts';
  import RowView from './RowView.svelte';
  import Wrap from './common/Wrap.svelte';

  let {indexId, sliceId, indexes, separator, debugIds, row}: SliceViewProps =
    $props();

  const {store, tableId} = getIndexStoreTableId(
    () => indexes,
    () => indexId,
  );
  const rowIds = createSliceRowIds(
    () => indexId,
    () => sliceId,
    () => indexes,
  );
</script>

<Wrap ids={rowIds.current} {separator} {debugIds} id={sliceId} custom={row}>
  {#snippet children(rowId)}
    {#if tableId}<RowView {tableId} {rowId} {store} {debugIds} />{/if}
  {/snippet}
</Wrap>

// src/ui-react/SliceView.tsx
import type {Id} from '../@types/index.d.ts';
import type {
  SliceProps,
  SliceView as SliceViewDecl,
} from '../@types/ui-react/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getIndexStoreTableId, getProps} from '../common/react.ts';
import {Wrap} from './common/Wrap.tsx';
import {useIndexesOrIndexesById, useSliceRowIds} from './hooks.ts';
import {RowView} from './RowView.tsx';

export const SliceView: typeof SliceViewDecl = ({
  indexId,
  sliceId,
  indexes,
  rowComponent: Row = RowView,
  getRowComponentProps,
  separator,
  debugIds,
}: SliceProps): any => {
  const [resolvedIndexes, store, tableId] = getIndexStoreTableId(
    useIndexesOrIndexesById(indexes),
    indexId,
  );
  const rowIds = useSliceRowIds(indexId, sliceId, resolvedIndexes);
  return (
    <Wrap separator={separator} debugIds={debugIds} id={sliceId}>
      {arrayMap(rowIds, (rowId) => (
        <Row
          key={rowId}
          {...getProps(getRowComponentProps, rowId)}
          tableId={tableId as Id}
          rowId={rowId}
          store={store}
          debugIds={debugIds}
        />
      ))}
    </Wrap>
  );
};
