// src/ui-solid/ValuesView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  ValuesProps,
} from '../@types/ui-solid/index.d.ts';
import type {Id} from '../@types/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {getProps, getValue} from '../common/solid.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useValueIds} from './hooks.ts';
import {ValueView} from './ValueView.tsx';

export const ValuesView = (props: ValuesProps): JSXElement => {
  const valueIds = useValueIds(() => props.store);
  return renderView(() => {
    const Value = props.valueComponent ?? ValueView;
    return wrap(
      arrayMap(getValue(valueIds) as Id[], (valueId: Id) => (
        <Value
          {...getProps(props.getValueComponentProps, valueId)}
          valueId={valueId}
          store={props.store}
          debugIds={props.debugIds}
        />
      )),
      props.separator,
    );
  });
};

// src/ui-react/ValuesView.tsx
import type {
  ValuesProps,
  ValuesView as ValuesViewDecl,
} from '../@types/ui-react/index.js';
import {arrayMap} from '../common/array.ts';
import {getProps} from '../common/react.ts';
import {wrap} from './common.tsx';
import {useValueIds} from './hooks.ts';
import {ValueView} from './ValueView.tsx';

export const ValuesView: typeof ValuesViewDecl = ({
  store,
  valueComponent: Value = ValueView,
  getValueComponentProps,
  separator,
  debugIds,
}: ValuesProps): any =>
  wrap(
    arrayMap(useValueIds(store), (valueId) => (
      <Value
        key={valueId}
        {...getProps(getValueComponentProps, valueId)}
        valueId={valueId}
        store={store}
        debugIds={debugIds}
      />
    )),
    separator,
  );
