// src/ui-solid/ValueView.tsx
/* @jsxImportSource solid-js */
import type {JSXElement} from 'solid-js';
import type {
  ValueProps,
} from '../@types/ui-solid/index.d.ts';
import {getValue} from '../common/solid.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {renderView, wrap} from './common/wrap.tsx';
import {useValue} from './hooks.ts';

export const ValueView = (props: ValueProps): JSXElement => {
  const value = useValue(
    () => props.valueId,
    () => props.store,
  );
  return renderView(() =>
    wrap(
      EMPTY_STRING + (getValue(value) ?? EMPTY_STRING),
      undefined,
      props.debugIds,
      props.valueId,
    ),
  );
};

// src/ui-react/ValueView.tsx
import type {
  ValueProps,
  ValueView as ValueViewDecl,
} from '../@types/ui-react/index.d.ts';
import {EMPTY_STRING} from '../common/strings.ts';
import {Wrap} from './common/Wrap.tsx';
import {useValue} from './hooks.ts';

export const ValueView: typeof ValueViewDecl = ({
  valueId,
  store,
  debugIds,
}: ValueProps): any => (
  <Wrap debugIds={debugIds} id={valueId}>
    {EMPTY_STRING + (useValue(valueId, store) ?? EMPTY_STRING)}
  </Wrap>
);
