// src/ui-react-inspector/ErrorBoundary.tsx
import {PureComponent} from '../common/react.ts';
import type {ErrorInfo, ReactNode} from 'react';

interface Props {
  readonly children: ReactNode;
}

interface State {
  e: 0 | 1;
}

export class ErrorBoundary extends PureComponent<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {e: 0};
  }

  static getDerivedStateFromError() {
    return {e: 1};
  }

  // eslint-disable-next-line react/no-arrow-function-lifecycle
  componentDidCatch = (error: Error, info: ErrorInfo) =>
    // eslint-disable-next-line no-console
    console.error(error, info.componentStack);

  render() {
    return this.state.e ? (
      <span className="warn">
        Inspector error: please see console for details.
      </span>
    ) : (
      this.props.children
    );
  }
}

// src/ui-svelte-inspector/ErrorBoundary.svelte
<script lang="ts">
  import type {Snippet} from 'svelte';

  type Props = {
    children: Snippet;
  };

  const {children}: Props = $props();

  const handleError = (error: unknown) =>
    // eslint-disable-next-line no-console
    console.error(error);
</script>

<svelte:boundary onerror={handleError}>
  {@render children()}
  {#snippet failed(_error, _reset)}
    <span class="warn">Inspector error: please see console for details.</span>
  {/snippet}
</svelte:boundary>
