// src/store-inspector/IndexesView.tsx
/** @jsx createElement */

import {arrayIsEmpty, arrayJoin, arrayMap} from '../common/array';
import {useIndexIds, useIndexes, useSliceIds} from '../ui-react';
import {DEFAULT} from '../common/strings';
import {Details} from './Details';
import {Id} from '../types/common';
import {IndexProps} from '../types/ui-react';
import {StoreProp} from './types';
import {createElement} from '../ui-react/common';
import {getUniqueId} from './common';
import {isUndefined} from '../common/other';

const IndexView = ({
  indexes,
  indexesId,
  indexId,
  s,
}: IndexProps & {readonly indexesId?: Id} & StoreProp) => (
  <Details
    uniqueId={getUniqueId('i', indexesId, indexId)}
    summary={'Index: ' + indexId}
    s={s}
  >
    {arrayJoin(useSliceIds(indexId, indexes), ', ')}
  </Details>
);

export const IndexesView = ({
  indexesId,
  s,
}: {readonly indexesId?: Id} & StoreProp) => {
  const indexes = useIndexes(indexesId);
  const indexIds = useIndexIds(indexes);
  return isUndefined(indexes) ? null : (
    <Details
      uniqueId={getUniqueId('i', indexesId)}
      summary={'Indexes: ' + (indexesId ?? DEFAULT)}
      s={s}
    >
      {arrayIsEmpty(indexIds)
        ? 'No indexes defined'
        : arrayMap(indexIds, (indexId) => (
            <IndexView
              indexes={indexes}
              indexesId={indexesId}
              indexId={indexId}
              s={s}
            />
          ))}
    </Details>
  );
};

// src/ui-svelte-inspector/IndexesView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import {DEFAULT} from '../common/strings.ts';
  import {getUniqueId, sortedIdsMap} from '../common/inspector/common.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {arrayIsEmpty} from '../common/array.ts';
  import {isUndefined} from '../common/other.ts';
  import {getIndexIds, getIndexes} from '../ui-svelte/functions.svelte.ts';
  import Details from './Details.svelte';
  import IndexView from './IndexView.svelte';

  type Props = {indexesId?: Id} & StoreProp;

  let {indexesId, s}: Props = $props();
  const indexes = $derived(getIndexes(indexesId));
  const indexIds = getIndexIds(() => indexes);
  const sortedIndexIds = $derived(
    sortedIdsMap(indexIds.current, (indexId) => indexId),
  );
  const title = $derived('Indexes: ' + (indexesId ?? DEFAULT));
</script>

{#if !isUndefined(indexes)}
  <Details uniqueId={getUniqueId('i', indexesId)} {title} {s}>
    {#if arrayIsEmpty(indexIds.current)}
      No indexes defined
    {:else}
      {#each sortedIndexIds as indexId (indexId)}
        <IndexView {indexes} {indexesId} {indexId} {s} />
      {/each}
    {/if}
  </Details>
{/if}
