// src/ui-react-dom/store-inspector/MetricsView.tsx
/** @jsx createElement */

import {arrayIsEmpty, arrayMap} from '../../common/array';
import {useMetric, useMetricIds, useMetrics} from '../../ui-react';
import {DEFAULT} from '../../common/strings';
import {Details} from './Details';
import type {Id} from '../../@types/common';
import type {MetricProps} from '../../@types/ui-react';
import type {Metrics} from '../../@types/metrics';
import type {StoreProp} from './types';
import {createElement} from '../../common/react';
import {getUniqueId} from './common';
import {isUndefined} from '../../common/other';

const MetricRow = ({metrics, metricId}: MetricProps) => (
  <tr>
    <th>{metricId}</th>
    <td>{(metrics as Metrics)?.getTableId(metricId)}</td>
    <td>{useMetric(metricId, metrics)}</td>
  </tr>
);

export const MetricsView = ({
  metricsId,
  s,
}: {readonly metricsId?: Id} & StoreProp) => {
  const metrics = useMetrics(metricsId);
  const metricIds = useMetricIds(metrics);
  return isUndefined(metrics) ? null : (
    <Details
      uniqueId={getUniqueId('m', metricsId)}
      summary={'Metrics: ' + (metricsId ?? DEFAULT)}
      s={s}
    >
      {arrayIsEmpty(metricIds) ? (
        'No metrics defined'
      ) : (
        <table>
          <thead>
            <th>Metric Id</th>
            <th>Table Id</th>
            <th>Metric</th>
          </thead>
          <tbody>
            {arrayMap(metricIds, (metricId) => (
              <MetricRow metrics={metrics} metricId={metricId} key={metricId} />
            ))}
          </tbody>
        </table>
      )}
    </Details>
  );
};

// src/ui-svelte-inspector/MetricsView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import {DEFAULT} from '../common/strings.ts';
  import {getUniqueId} from '../common/inspector/common.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {arrayIsEmpty} from '../common/array.ts';
  import {isUndefined} from '../common/other.ts';
  import {getMetricIds, getMetrics} from '../ui-svelte/functions.svelte.ts';
  import MetricView from '../ui-svelte/MetricView.svelte';
  import Details from './Details.svelte';

  type Props = {metricsId?: Id} & StoreProp;

  let {metricsId, s}: Props = $props();
  const metrics = $derived(getMetrics(metricsId));
  const metricIds = getMetricIds(() => metrics);
  const title = $derived('Metrics: ' + (metricsId ?? DEFAULT));
</script>

{#if !isUndefined(metrics)}
  <Details uniqueId={getUniqueId('m', metricsId)} {title} {s}>
    {#if arrayIsEmpty(metricIds.current)}
      No metrics defined
    {:else}
      <table>
        <thead>
          <tr>
            <th>Metric Id</th>
            <th>Table Id</th>
            <th>Metric</th>
          </tr>
        </thead>
        <tbody>
          {#each metricIds.current as metricId (metricId)}
            <tr>
              <th title={metricId}>{metricId}</th>
              <td>{metrics?.getTableId(metricId)}</td>
              <td><MetricView {metricId} {metrics} /></td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </Details>
{/if}
