// src/ui-react-dom/store-inspector/Panel.tsx
/** @jsx createElement */

import {OPEN_VALUE, POSITION_VALUE} from './common';
import {Body} from './Body';
import {ErrorBoundary} from './ErrorBoundary';
import {Header} from './Header';
import type {StoreProp} from './types';
import {createElement} from '../../common/react';
import {useValue} from '../../ui-react';

export const Panel = ({s}: StoreProp) => {
  const position = useValue(POSITION_VALUE, s) ?? 1;

  return useValue(OPEN_VALUE, s) ? (
    <main data-position={position}>
      <Header s={s} />
      <ErrorBoundary>
        <Body s={s} />
      </ErrorBoundary>
    </main>
  ) : null;
};

// src/ui-svelte-inspector/Panel.svelte
<script lang="ts">
  import {getValue} from '../ui-svelte/functions.svelte.ts';
  import Body from './Body.svelte';
  import ErrorBoundary from './ErrorBoundary.svelte';
  import Header from './Header.svelte';
  import {OPEN_VALUE, POSITION_VALUE} from './common.ts';
  import type {StoreProp} from './types.ts';

  let {s}: StoreProp = $props();

  const position = getValue(
    () => POSITION_VALUE,
    () => s,
  );
  const open = getValue(
    () => OPEN_VALUE,
    () => s,
  );
</script>

{#if open.current}
  <main data-position={position.current ?? 1}>
    <Header {s} />
    <ErrorBoundary>
      <Body {s} />
    </ErrorBoundary>
  </main>
{/if}
