// src/store-inspector/QueriesView.tsx
/** @jsx createElement */

import {getUniqueId, sortedIdsMap} from './common';
import {useQueries, useQueryIds} from '../ui-react';
import {DEFAULT} from '../common/strings';
import {Details} from './Details';
import {Id} from '../types/common';
import {Queries} from '../types/queries';
import {ResultSortedTableInHtmlTable} from '../ui-react/dom';
import {StoreProp} from './types';
import {arrayIsEmpty} from '../common/array';
import {createElement} from '../ui-react/common';
import {isUndefined} from '../common/other';

const QueryView = ({
  queries,
  queriesId,
  queryId,
  s,
}: {
  readonly queries?: Queries | undefined;
  readonly queriesId?: Id;
  readonly queryId: Id;
} & StoreProp) => {
  return (
    <Details
      uniqueId={getUniqueId('q', queriesId, queryId)}
      summary={'Query: ' + queryId}
      s={s}
    >
      <ResultSortedTableInHtmlTable queryId={queryId} queries={queries} />
    </Details>
  );
};

export const QueriesView = ({
  queriesId,
  s,
}: {readonly queriesId?: Id} & StoreProp) => {
  const queries = useQueries(queriesId);
  const queryIds = useQueryIds(queries);
  return isUndefined(queries) ? null : (
    <Details
      uniqueId={getUniqueId('q', queriesId)}
      summary={'Queries: ' + (queriesId ?? DEFAULT)}
      s={s}
    >
      {arrayIsEmpty(queryIds)
        ? 'No queries defined'
        : sortedIdsMap(queryIds, (queryId) => (
            <QueryView
              queries={queries}
              queriesId={queriesId}
              queryId={queryId}
              s={s}
            />
          ))}
    </Details>
  );
};

// src/ui-svelte-inspector/QueriesView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import {DEFAULT} from '../common/strings.ts';
  import {getUniqueId, sortedIdsMap} from '../common/inspector/common.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {arrayIsEmpty} from '../common/array.ts';
  import {isUndefined} from '../common/other.ts';
  import {getQueries, getQueryIds} from '../ui-svelte/functions.svelte.ts';
  import Details from './Details.svelte';
  import QueryView from './QueryView.svelte';

  type Props = {queriesId?: Id} & StoreProp;

  let {queriesId, s}: Props = $props();
  const queries = $derived(getQueries(queriesId));
  const queryIds = getQueryIds(() => queries);
  const sortedQueryIds = $derived(
    sortedIdsMap(queryIds.current, (queryId) => queryId),
  );
  const title = $derived('Queries: ' + (queriesId ?? DEFAULT));
</script>

{#if !isUndefined(queries)}
  <Details uniqueId={getUniqueId('q', queriesId)} {title} {s}>
    {#if arrayIsEmpty(queryIds.current)}
      No queries defined
    {:else}
      {#each sortedQueryIds as queryId (queryId)}
        <QueryView {queries} {queriesId} {queryId} {s} />
      {/each}
    {/if}
  </Details>
{/if}
