// src/store-inspector/StoreView.tsx
/** @jsx createElement */

import {ExtraProps, TableProps} from '../types/ui-react';
import {TablesView, useStore} from '../ui-react';
import {getUniqueId, useToggle} from './common';
import {DEFAULT} from '../common/strings';
import {Id} from '../types/common';
import React from 'react';
import {SortedTableInHtmlTable} from '../ui-react/dom';
import {StoreProp} from './types';
import {createElement} from '../ui-react/common';
import {isUndefined} from '../common/other';

const {useCallback} = React;

const TableView = ({storeId, s, ...props}: TableProps & ExtraProps) => {
  const [open, handleToggle] = useToggle(
    'table',
    getUniqueId(storeId, props.tableId),
    s,
  );
  return (
    <details open={open} onToggle={handleToggle}>
      <summary>Table: {props.tableId}</summary>
      <SortedTableInHtmlTable
        {...props}
        limit={10}
        paginator={true}
        sortOnClick={true}
        editable={true}
      />
    </details>
  );
};

export const StoreView = ({
  storeId,
  s,
}: {readonly storeId?: Id} & StoreProp) => {
  const store = useStore(storeId);
  const [open, handleToggle] = useToggle('store', getUniqueId(storeId), s);
  const getTableComponentProps = useCallback(
    () => ({storeId, s: s}),
    [storeId, s],
  );

  return isUndefined(store) ? null : (
    <details open={open} onToggle={handleToggle}>
      <summary>Store: {storeId ?? DEFAULT}</summary>
      <TablesView
        store={store}
        tableComponent={TableView}
        getTableComponentProps={getTableComponentProps}
      />
    </details>
  );
};

// src/ui-svelte-inspector/StoreView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import {getUniqueId} from '../common/inspector/common.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {isUndefined} from '../common/other.ts';
  import {DEFAULT} from '../common/strings.ts';
  import {getStore} from '../ui-svelte/functions.svelte.ts';
  import Details from './Details.svelte';
  import TablesView from './TablesView.svelte';
  import ValuesView from './ValuesView.svelte';

  type Props = {storeId?: Id} & StoreProp;

  let {storeId, s}: Props = $props();
  const store = $derived(getStore(storeId));
  const title = $derived(
    (store?.isMergeable() ? 'Mergeable' : '') +
      'Store: ' +
      (storeId ?? DEFAULT),
  );
</script>

{#if !isUndefined(store)}
  <Details uniqueId={getUniqueId('s', storeId)} {title} {s}>
    <ValuesView {store} {storeId} {s} />
    <TablesView {store} {storeId} {s} />
  </Details>
{/if}
