// src/ui-svelte-inspector/RelationshipsView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import {DEFAULT} from '../common/strings.ts';
  import {getUniqueId, sortedIdsMap} from '../common/inspector/common.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {arrayIsEmpty} from '../common/array.ts';
  import {isUndefined} from '../common/other.ts';
  import {
    getRelationshipIds,
    getRelationships,
  } from '../ui-svelte/functions.svelte.ts';
  import Details from './Details.svelte';
  import RelationshipView from './RelationshipView.svelte';

  type Props = {relationshipsId?: Id} & StoreProp;

  let {relationshipsId, s}: Props = $props();
  const relationships = $derived(getRelationships(relationshipsId));
  const relationshipIds = getRelationshipIds(() => relationships);
  const sortedRelationshipIds = $derived(
    sortedIdsMap(relationshipIds.current, (relationshipId) => relationshipId),
  );
  const title = $derived('Relationships: ' + (relationshipsId ?? DEFAULT));
</script>

{#if !isUndefined(relationships)}
  <Details uniqueId={getUniqueId('r', relationshipsId)} {title} {s}>
    {#if arrayIsEmpty(relationshipIds.current)}
      No relationships defined
    {:else}
      {#each sortedRelationshipIds as relationshipId (relationshipId)}
        <RelationshipView
          {relationships}
          {relationshipsId}
          {relationshipId}
          {s}
        />
      {/each}
    {/if}
  </Details>
{/if}

// src/ui-react-dom/store-inspector/RelationshipsView.tsx
/** @jsx createElement */

import {getUniqueId, sortedIdsMap, useEditable} from './common';
import {useRelationshipIds, useRelationships} from '../../ui-react';
import {DEFAULT} from '../../common/strings';
import {Details} from './Details';
import type {Id} from '../../@types/common';
import {RelationshipInHtmlTable} from '../components';
import type {Relationships} from '../../@types/relationships';
import type {StoreProp} from './types';
import {arrayIsEmpty} from '../../common/array';
import {createElement} from '../../common/react';
import {isUndefined} from '../../common/other';

const RelationshipView = ({
  relationships,
  relationshipsId,
  relationshipId,
  s,
}: {
  readonly relationships?: Relationships | undefined;
  readonly relationshipsId?: Id;
  readonly relationshipId: Id;
} & StoreProp) => {
  const uniqueId = getUniqueId('r', relationshipsId, relationshipId);
  const [editable, handleEditable] = useEditable(uniqueId, s);
  return (
    <Details
      uniqueId={uniqueId}
      summary={'Relationship: ' + relationshipId}
      editable={editable}
      handleEditable={handleEditable}
      s={s}
    >
      <RelationshipInHtmlTable
        relationshipId={relationshipId}
        relationships={relationships}
        editable={editable}
      />
    </Details>
  );
};

export const RelationshipsView = ({
  relationshipsId,
  s,
}: {readonly relationshipsId?: Id} & StoreProp) => {
  const relationships = useRelationships(relationshipsId);
  const relationshipIds = useRelationshipIds(relationships);
  return isUndefined(relationships) ? null : (
    <Details
      uniqueId={getUniqueId('r', relationshipsId)}
      summary={'Relationships: ' + (relationshipsId ?? DEFAULT)}
      s={s}
    >
      {arrayIsEmpty(relationshipIds)
        ? 'No relationships defined'
        : sortedIdsMap(relationshipIds, (relationshipId) => (
            <RelationshipView
              relationships={relationships}
              relationshipsId={relationshipsId}
              relationshipId={relationshipId}
              s={s}
              key={relationshipId}
            />
          ))}
    </Details>
  );
};
