// src/ui-svelte-inspector/StoreView.svelte
<script lang="ts">
  import type {Id} from '../@types/common/index.d.ts';
  import {getUniqueId} from '../common/inspector/common.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {isUndefined} from '../common/other.ts';
  import {DEFAULT} from '../common/strings.ts';
  import {getStore} from '../ui-svelte/functions.svelte.ts';
  import Details from './Details.svelte';
  import TablesView from './TablesView.svelte';
  import ValuesView from './ValuesView.svelte';

  type Props = {storeId?: Id} & StoreProp;

  let {storeId, s}: Props = $props();
  const store = $derived(getStore(storeId));
  const title = $derived(
    (store?.isMergeable() ? 'Mergeable' : '') +
      'Store: ' +
      (storeId ?? DEFAULT),
  );
</script>

{#if !isUndefined(store)}
  <Details uniqueId={getUniqueId('s', storeId)} {title} {s}>
    <ValuesView {store} {storeId} {s} />
    <TablesView {store} {storeId} {s} />
  </Details>
{/if}

// src/ui-react-inspector/StoreView.tsx
import type {Id} from '../@types/common/index.d.ts';
import {getUniqueId} from '../common/inspector/common.ts';
import type {StoreProp} from '../common/inspector/types.ts';
import {isUndefined} from '../common/other.ts';
import {DEFAULT} from '../common/strings.ts';
import {useStore} from '../ui-react/index.ts';
import {Details} from './Details.tsx';
import {TablesView} from './TablesView.tsx';
import {ValuesView} from './ValuesView.tsx';

export const StoreView = ({
  storeId,
  s,
}: {readonly storeId?: Id} & StoreProp) => {
  const store = useStore(storeId);
  return isUndefined(store) ? null : (
    <Details
      uniqueId={getUniqueId('s', storeId)}
      title={
        (store.isMergeable() ? 'Mergeable' : '') +
        'Store: ' +
        (storeId ?? DEFAULT)
      }
      s={s}
    >
      <ValuesView storeId={storeId} store={store} s={s} />
      <TablesView storeId={storeId} store={store} s={s} />
    </Details>
  );
};
