// src/ui-react-dom/RelationshipInHtmlTable.tsx
import type {Id, Store} from '../@types/index.d.ts';
import type {
  HtmlTableProps,
  RelationshipInHtmlTableProps,
} from '../@types/ui-react-dom/index.d.ts';
import type {RowProps} from '../@types/ui-react/index.d.ts';
import {arrayMap} from '../common/array.ts';
import {objToArray} from '../common/obj.ts';
import {isFalse, isUndefined} from '../common/other.ts';
import {getProps, getRelationshipsStoreTableIds} from '../common/react.ts';
import {DOT, strSplit} from '../common/strings.ts';
import {
  useRelationshipsOrRelationshipsById,
  useRemoteRowId,
  useRowIds,
  useTableCellIds,
} from '../ui-react/hooks.ts';
import {CellView} from '../ui-react/index.ts';
import {EditableCellView} from './EditableCellView.tsx';
import {useCells, useParams} from './common/hooks.tsx';
import {
  extraHeaders,
  extraRowCells,
  RelationshipInHtmlRowParams,
} from './common/index.tsx';

const useDottedCellIds = (tableId: Id | undefined, store: Store | undefined) =>
  arrayMap(
    useTableCellIds(tableId as Id, store),
    (cellId) => tableId + DOT + cellId,
  );

const RelationshipInHtmlRow = ({
  localRowId,
  params: [
    idColumn,
    cells,
    localTableId,
    remoteTableId,
    relationshipId,
    relationships,
    store,
    extraCellsBefore,
    extraCellsAfter,
  ],
}: {
  readonly localRowId: Id;
  readonly params: RelationshipInHtmlRowParams;
}) => {
  const remoteRowId = useRemoteRowId(
    relationshipId,
    localRowId,
    relationships,
  ) as Id;
  const rowProps: RowProps = {
    tableId: localTableId ?? '',
    rowId: localRowId,
    store,
  };
  return (
    <tr>
      {extraRowCells(extraCellsBefore, rowProps)}
      {isFalse(idColumn) ? null : (
        <>
          <th title={localRowId}>{localRowId}</th>
          <th title={remoteRowId}>{remoteRowId}</th>
        </>
      )}
      {objToArray(
        cells,
        ({component: CellView, getComponentProps}, compoundCellId) => {
          const [tableId, cellId] = strSplit(compoundCellId, DOT, 2);
          const rowId =
            tableId === localTableId
              ? localRowId
              : tableId === remoteTableId
                ? remoteRowId
                : undefined;
          return isUndefined(rowId) ? null : (
            <td key={compoundCellId}>
              <CellView
                {...getProps(getComponentProps, rowId, cellId)}
                store={store}
                tableId={tableId}
                rowId={rowId}
                cellId={cellId}
              />
            </td>
          );
        },
      )}
      {extraRowCells(extraCellsAfter, rowProps, 1)}
    </tr>
  );
};

export const RelationshipInHtmlTable = ({
  relationshipId,
  relationships,
  editable,
  customCells,
  extraCellsBefore,
  extraCellsAfter,
  className,
  headerRow,
  idColumn = true,
}: RelationshipInHtmlTableProps & HtmlTableProps): any => {
  const [resolvedRelationships, store, localTableId, remoteTableId] =
    getRelationshipsStoreTableIds(
      useRelationshipsOrRelationshipsById(relationships),
      relationshipId,
    );
  const cells = useCells(
    [
      ...useDottedCellIds(localTableId, store),
      ...useDottedCellIds(remoteTableId, store),
    ],
    customCells,
    editable ? EditableCellView : CellView,
  );
  const params = useParams(
    idColumn,
    cells,
    localTableId,
    remoteTableId,
    relationshipId,
    resolvedRelationships,
    store,
    extraCellsBefore,
    extraCellsAfter,
  );
  return (
    <table className={className}>
      {isFalse(headerRow) ? null : (
        <thead>
          <tr>
            {extraHeaders(extraCellsBefore)}
            {isFalse(idColumn) ? null : (
              <>
                <th>{localTableId}.Id</th>
                <th>{remoteTableId}.Id</th>
              </>
            )}
            {objToArray(cells, ({label}, cellId) => (
              <th key={cellId}>{label}</th>
            ))}
            {extraHeaders(extraCellsAfter, 1)}
          </tr>
        </thead>
      )}
      <tbody>
        {arrayMap(useRowIds(localTableId as Id, store), (localRowId) => (
          <RelationshipInHtmlRow
            key={localRowId}
            localRowId={localRowId}
            params={params}
          />
        ))}
      </tbody>
    </table>
  );
};

// src/ui-svelte-dom/RelationshipInHtmlTable.svelte
<script lang="ts">
  import type {
    HtmlTableProps,
    RelationshipInHtmlTableProps,
  } from '../@types/ui-svelte-dom/index.d.ts';
  import {arrayMap} from '../common/array.ts';
  import {objEntries} from '../common/obj.ts';
  import {isFalse} from '../common/other.ts';
  import {DOT} from '../common/strings.ts';
  import {
    getRelationshipsStoreTableIds,
    getRowIds,
    getTableCellIds,
  } from '../ui-svelte/functions.svelte.ts';
  import CellView from '../ui-svelte/CellView.svelte';
  import EditableCellView from './EditableCellView.svelte';
  import RelationshipInHtmlRow from './RelationshipInHtmlRow.svelte';
  import {getCells, getExtraHeaders} from './common/index.ts';

  let {
    relationshipId,
    relationships,
    editable,
    customCells,
    extraCellsBefore = [],
    extraCellsAfter = [],
    className,
    headerRow,
    idColumn = true,
  }: RelationshipInHtmlTableProps & HtmlTableProps = $props();

  const relationship = getRelationshipsStoreTableIds(
    () => relationships,
    () => relationshipId,
  );
  const localCellIds = getTableCellIds(
    () => relationship.localTableId as any,
    () => relationship.store,
  );
  const remoteCellIds = getTableCellIds(
    () => relationship.remoteTableId as any,
    () => relationship.store,
  );
  const localRowIds = getRowIds(
    () => relationship.localTableId as any,
    () => relationship.store,
  );
  const defaultCellComponent = $derived(editable ? EditableCellView : CellView);
  const cells = $derived(
    getCells(
      [
        ...arrayMap(
          localCellIds.current,
          (cellId) => relationship.localTableId + DOT + cellId,
        ),
        ...arrayMap(
          remoteCellIds.current,
          (cellId) => relationship.remoteTableId + DOT + cellId,
        ),
      ],
      customCells,
      defaultCellComponent,
    ),
  );
  const cellEntries = $derived(objEntries(cells));
  const extraHeadersBefore = $derived(getExtraHeaders(extraCellsBefore));
  const extraHeadersAfter = $derived(getExtraHeaders(extraCellsAfter, 1));
</script>

<table class={className}>
  {#if headerRow !== false}
    <thead>
      <tr>
        {#each extraHeadersBefore as extraHeader (extraHeader.key)}
          <th class={extraHeader.className}>{extraHeader.label}</th>
        {/each}
        {#if !isFalse(idColumn)}
          <th>{relationship.localTableId}.Id</th>
          <th>{relationship.remoteTableId}.Id</th>
        {/if}
        {#each cellEntries as entry (entry[0])}
          <th>{entry[1].label}</th>
        {/each}
        {#each extraHeadersAfter as extraHeader (extraHeader.key)}
          <th class={extraHeader.className}>{extraHeader.label}</th>
        {/each}
      </tr>
    </thead>
  {/if}
  <tbody>
    {#each localRowIds.current as localRowId (localRowId)}
      <RelationshipInHtmlRow
        {localRowId}
        {idColumn}
        {cells}
        localTableId={relationship.localTableId}
        remoteTableId={relationship.remoteTableId}
        {relationshipId}
        {relationships}
        store={relationship.store}
        {extraCellsBefore}
        {extraCellsAfter}
      />
    {/each}
  </tbody>
</table>
