// src/ui-react-dom/ResultTableInHtmlTable.tsx
import type {
  HtmlTableProps,
  ResultTableInHtmlTable as ResultTableInHtmlTableDecl,
  ResultTableInHtmlTableProps,
} from '../@types/ui-react-dom/index.js';
import {useResultRowIds, useResultTableCellIds} from '../ui-react/hooks.ts';
import {ResultCellView} from '../ui-react/index.ts';
import {
  HtmlTable,
  useCells,
  useParams,
  useQueriesCellComponentProps,
} from './common.tsx';

export const ResultTableInHtmlTable: typeof ResultTableInHtmlTableDecl = ({
  queryId,
  queries,
  customCells,
  extraCellsBefore,
  extraCellsAfter,
  ...props
}: ResultTableInHtmlTableProps & HtmlTableProps): any => (
  <HtmlTable
    {...props}
    params={useParams(
      useCells(
        useResultTableCellIds(queryId, queries),
        customCells,
        ResultCellView,
      ),
      useQueriesCellComponentProps(queries, queryId),
      useResultRowIds(queryId, queries),
      extraCellsBefore,
      extraCellsAfter,
    )}
  />
);

// src/ui-svelte-dom/ResultTableInHtmlTable.svelte
<script lang="ts">
  import type {
    HtmlTableProps,
    ResultTableInHtmlTableProps,
  } from '../@types/ui-svelte-dom/index.d.ts';
  import {
    getResultRowIds,
    getResultTableCellIds,
  } from '../ui-svelte/functions.svelte.ts';
  import ResultCellView from '../ui-svelte/ResultCellView.svelte';
  import HtmlTable from './common/HtmlTable.svelte';
  import {getCells} from './common/index.ts';

  let {
    queryId,
    queries,
    customCells,
    extraCellsBefore,
    extraCellsAfter,
    ...props
  }: ResultTableInHtmlTableProps & HtmlTableProps = $props();

  const defaultCellIds = getResultTableCellIds(
    () => queryId,
    () => queries,
  );
  const rowIds = getResultRowIds(
    () => queryId,
    () => queries,
  );
  const cells = $derived(
    getCells(defaultCellIds.current, customCells, ResultCellView),
  );
  const cellComponentProps = $derived({queries, queryId});
</script>

<HtmlTable
  {...props}
  {cells}
  {cellComponentProps}
  {rowIds}
  {extraCellsBefore}
  {extraCellsAfter}
/>
