// src/ui-svelte-inspector/Body.svelte
<script lang="ts">
  import {onDestroy} from 'svelte';
  import {
    NO_PROVIDED_OBJECTS_MESSAGE,
  } from '../common/inspector/common.ts';
  import {
    cancelInspectorIdleCallback,
    requestInspectorIdleCallback,
  } from '../common/inspector/idle.ts';
  import type {StoreProp} from '../common/inspector/types.ts';
  import {arrayIsEmpty} from '../common/array.ts';
  import {isUndefined, mathFloor} from '../common/other.ts';
  import {
    getIndexes,
    getIndexesIds,
    getMetrics,
    getMetricsIds,
    getQueries,
    getQueriesIds,
    getRelationships,
    getRelationshipsIds,
    getStore,
    getStoreIds,
    getValues,
  } from '../ui-svelte/functions.svelte.ts';
  import IndexesView from './IndexesView.svelte';
  import MetricsView from './MetricsView.svelte';
  import QueriesView from './QueriesView.svelte';
  import RelationshipsView from './RelationshipsView.svelte';
  import StoreView from './StoreView.svelte';

  let {s}: StoreProp = $props();

  const store = getStore();
  const storeIds = getStoreIds();
  const metrics = getMetrics();
  const metricsIds = getMetricsIds();
  const indexes = getIndexes();
  const indexesIds = getIndexesIds();
  const relationships = getRelationships();
  const relationshipsIds = getRelationshipsIds();
  const queries = getQueries();
  const queriesIds = getQueriesIds();
  const values = getValues(() => s);

  let article = $state<HTMLElement | undefined>(undefined);
  let scrolled = $state(false);
  let idleCallback = 0;

  $effect(() => {
    const articleElement = article;
    const {scrollLeft = 0, scrollTop = 0} = values.current;

    if (articleElement && !scrolled) {
      const observer = new MutationObserver(() => {
        if (
          articleElement.scrollWidth >=
            mathFloor(Number(scrollLeft)) + articleElement.clientWidth &&
          articleElement.scrollHeight >=
            mathFloor(Number(scrollTop)) + articleElement.clientHeight
        ) {
          articleElement.scrollTo(Number(scrollLeft), Number(scrollTop));
        }
      });
      observer.observe(articleElement, {childList: true, subtree: true});

      return () => observer.disconnect();
    }
  });

  onDestroy(() => cancelInspectorIdleCallback(idleCallback));

  const handleScroll = (event: Event) => {
    const {scrollLeft, scrollTop} = event.currentTarget as HTMLElement;
    cancelInspectorIdleCallback(idleCallback);
    idleCallback = requestInspectorIdleCallback(() => {
      scrolled = true;
      s.setPartialValues({scrollLeft, scrollTop});
    });
  };
</script>

{#if isUndefined(store) &&
  arrayIsEmpty(storeIds.current) &&
  isUndefined(metrics) &&
  arrayIsEmpty(metricsIds.current) &&
  isUndefined(indexes) &&
  arrayIsEmpty(indexesIds.current) &&
  isUndefined(relationships) &&
  arrayIsEmpty(relationshipsIds.current) &&
  isUndefined(queries) &&
  arrayIsEmpty(queriesIds.current)}
  <span class="warn">
    {NO_PROVIDED_OBJECTS_MESSAGE}
  </span>
{:else}
  <article bind:this={article} onscroll={handleScroll}>
    <StoreView {s} />
    {#each storeIds.current as storeId (storeId)}
      <StoreView {storeId} {s} />
    {/each}
    <MetricsView {s} />
    {#each metricsIds.current as metricsId (metricsId)}
      <MetricsView {metricsId} {s} />
    {/each}
    <IndexesView {s} />
    {#each indexesIds.current as indexesId (indexesId)}
      <IndexesView {indexesId} {s} />
    {/each}
    <RelationshipsView {s} />
    {#each relationshipsIds.current as relationshipsId (relationshipsId)}
      <RelationshipsView {relationshipsId} {s} />
    {/each}
    <QueriesView {s} />
    {#each queriesIds.current as queriesId (queriesId)}
      <QueriesView {queriesId} {s} />
    {/each}
  </article>
{/if}

// src/store-inspector/Body.tsx
/** @jsx createElement */

import {arrayIsEmpty, arrayMap} from '../common/array';
import {
  createElement,
  useCallback,
  useLayoutEffect,
  useRef,
  useState,
} from '../ui-react/common';
import {isUndefined, mathFloor} from '../common/other';
import {
  useIndexes,
  useIndexesIds,
  useMetrics,
  useMetricsIds,
  useQueries,
  useQueriesIds,
  useRelationships,
  useRelationshipsIds,
  useStore,
  useStoreIds,
  useValues,
} from '../ui-react';
import {CURRENT_TARGET} from '../common/strings';
import {IndexesView} from './IndexesView';
import {MetricsView} from './MetricsView';
import {QueriesView} from './QueriesView';
import {RelationshipsView} from './RelationshipsView';
import {StoreProp} from './types';
import {StoreView} from './StoreView';
import {SyntheticEvent} from 'react';

export const Body = ({s}: StoreProp) => {
  const articleRef = useRef<HTMLElement>(null);
  const idleCallbackRef = useRef<number>(0);
  const [scrolled, setScrolled] = useState(false);
  const {scrollLeft, scrollTop} = useValues(s);

  useLayoutEffect(() => {
    const article = articleRef.current;
    if (article && !scrolled) {
      const observer = new MutationObserver(() => {
        if (
          article.scrollWidth >=
            mathFloor(scrollLeft as number) + article.clientWidth &&
          article.scrollHeight >=
            mathFloor(scrollTop as number) + article.clientHeight
        ) {
          article.scrollTo(scrollLeft as number, scrollTop as number);
        }
      });
      observer.observe(article, {childList: true, subtree: true});
      return () => observer.disconnect();
    }
  }, [scrolled, scrollLeft, scrollTop]);

  const handleScroll = useCallback(
    (event: SyntheticEvent<HTMLElement>) => {
      const {scrollLeft, scrollTop} = event[CURRENT_TARGET];
      cancelIdleCallback(idleCallbackRef.current);
      idleCallbackRef.current = requestIdleCallback(() => {
        setScrolled(true);
        s.setPartialValues({scrollLeft, scrollTop});
      });
    },
    [s],
  );

  const store = useStore();
  const storeIds = useStoreIds();
  const metrics = useMetrics();
  const metricsIds = useMetricsIds();
  const indexes = useIndexes();
  const indexesIds = useIndexesIds();
  const relationships = useRelationships();
  const relationshipsIds = useRelationshipsIds();
  const queries = useQueries();
  const queriesIds = useQueriesIds();

  return isUndefined(store) &&
    arrayIsEmpty(storeIds) &&
    isUndefined(metrics) &&
    arrayIsEmpty(metricsIds) &&
    isUndefined(indexes) &&
    arrayIsEmpty(indexesIds) &&
    isUndefined(relationships) &&
    arrayIsEmpty(relationshipsIds) &&
    isUndefined(queries) &&
    arrayIsEmpty(queriesIds) ? (
    <span className="warn">
      There are no Stores or other objects to inspect. Make sure you placed the
      StoreInspector inside a Provider component.
    </span>
  ) : (
    <article ref={articleRef} onScroll={handleScroll}>
      <StoreView s={s} />
      {arrayMap(storeIds, (storeId) => (
        <StoreView storeId={storeId} s={s} key={storeId} />
      ))}
      <MetricsView s={s} />
      {arrayMap(metricsIds, (metricsId) => (
        <MetricsView metricsId={metricsId} s={s} key={metricsId} />
      ))}
      <IndexesView s={s} />
      {arrayMap(indexesIds, (indexesId) => (
        <IndexesView indexesId={indexesId} s={s} key={indexesId} />
      ))}
      <RelationshipsView s={s} />
      {arrayMap(relationshipsIds, (relationshipsId) => (
        <RelationshipsView
          relationshipsId={relationshipsId}
          s={s}
          key={relationshipsId}
        />
      ))}
      <QueriesView s={s} />
      {arrayMap(queriesIds, (queriesId) => (
        <QueriesView queriesId={queriesId} s={s} key={queriesId} />
      ))}
    </article>
  );
};
